annotator:
  ## Paths to source data
  genome_reads: 'data/datasets/p57_RNA_to_DNA/p57_bw2_sorted.bam'

  genome: 'data/DNA_scaffolds.fa'
  blast_hits: 'data/kinetoplastid_proteoms_bl_report_best_frames_extracted.csv'
  transcriptome: 'data/jaccard_Trinity.fasta_bl_report_best.csv'
  sl_mapping: 'data/SL_trimmered/p57_trimmed_sl_sorted.bed'

  # genome: 'tmp/DNA_scaffolds_NODE_1.fa'
  # blast_hits: 'tmp/blast_hits_NODE_1.csv'
  # transcriptome: 'tmp/transcriptome_NODE_1.csv'
  # sl_mapping: 'tmp/p57_trimmed_sl_sorted_NODE_1.bed'

  ## Main settings
  max_evalue: 0.0000000001
  # max_evalue: 0.01
  skip_preparation: true
  tmp_dir: 'tmp/annotator'
  blast_hit_target: 'subject'
  blast_hit_mode: 'genome'
  clustering_max_distance: 64
  sl_mapping_clustering_max_distance: 5
  zoi_sl_searching_inner_threshold: 100
  zoi_sl_searching_outer_threshold: 10

  polycistronic_sl_threshold: 15

  ## Transcriptome filtering
  transcriptome_min_size: 100
